print('----------------------------------------------')
verb = input('Please enter a Verb ')
print()
verb2 = input('Please enter a Verb ')
print()
verb3 = input('Please enter a Verb ')
print()
animal = input('Please enter a Animal ')
print()
exclamation = input('Please enter a Exclamation ')
print()
adjective = input('Please enter a Adjective ')
print('---------------------------------------------')
print()
print()
print('-----------------------------------------------------------------------------------------------------------------------')
print('Story 1')
print()
print(f'The other day, I was really in trouble. It all started when I saw a very')
print(f'{adjective} {animal} {verb3} down the hallway."{exclamation.capitalize()}!" I yelled. But all')
print(f'I could think to do was to {verb} over and over Miraculously,')
print(f'that caused it to stop, but not before it tried to {verb2}')
print('right in front of my family.')
print('-----------------------------------------------------------------------------------------------------------------------')
print()
print()
print('----------------------------------------------')
verb = input('Please enter a Verb ')
print()
verb2 = input('Please enter a Verb ')
print()
verb3 = input('Please enter a Verb ')
print()
verb4 = input('Please enter a Verb ')
print()
noun = input('Please enter a Noun ')
print()
noun2 = input('Please enter a Noun ')
print()
adverb = input('Please enter a Adverb ')
print()
adjective = input('Please enter a Adjective ')
print('---------------------------------------------')
print()
print()
print('-----------------------------------------------------------------------------------------------------------------------')
print('Story 2')
print()
print(f'One day I was {verb} then all of a sudden there was a {noun}.')
print(f'I was shocked at first but then I was discretely {verb2} but it was to late')
print(f'{noun} was {verb3} {adverb}, I was scared now. But luckily I had {noun2},')
print(f'I used {noun2} against {noun} and it got so {adjective} that it {verb4}.')
print('The end.')
print('-----------------------------------------------------------------------------------------------------------------------')
end = input()